---
functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории.
- Пользователь должен иметь возможность фильтровать товары
- Сайт должен иметь мобильную версию.
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
non-functional:
- Сайт должен быть безопасным и защищать данные пользователя.
- Сайт должен быть способен обрабатывать большое количество трафика
- Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
implicit:
- Сайт должен быть доступен на различных устройствах
- Сайт должен быть протестирован на совместимость с последними версиями браузеров.
- Сайт должен иметь локализацию на пользователя
- Сайт должен отображать местопоожение клиента
- Пользователь должен быть оповещен о поступлении интрересующего товара и акциях
